apiVersion: apps/v1
kind: Deployment
metadata:
  name: egress-sample
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: egress-sample
  template:
    metadata:
      labels:
        app: egress-sample
      annotations:
        kubernetes.azure.com/static-gateway-configuration: gateway-config
    spec:
      containers:
      - name: curl
        image: curlimages/curl:latest
        command: ["sleep","infinity"]
        resources: {}